import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Manual sidebar for the ROS 2 educational content
  module1Sidebar: [
    {
      type: 'category',
      label: 'Module 1: The Robotic Nervous System (ROS 2)',
      items: [
        'module-1/intro-to-ros2',
        'module-1/ros2-communication-model',
        'module-1/urdf-humanoids',
      ],
    },
  ],

  // Manual sidebar for the Digital Twin simulation content
  module2Sidebar: [
    {
      type: 'category',
      label: 'Module 2: The Digital Twin (Gazebo & Unity)',
      items: [
        'module-2/intro-to-digital-twins',
        'module-2/gazebo-physics-simulation',
        'module-2/unity-interaction-sensors',
      ],
    },
  ],

  // Manual sidebar for the AI-Robot Brain content
  module3Sidebar: [
    {
      type: 'category',
      label: 'Module 3: The AI-Robot Brain (NVIDIA Isaac™)',
      items: [
        'module-3/intro-to-ai-robot-brain',
        'module-3/perception-simulation-isaac-sim',
        'module-3/navigation-intelligence',
      ],
    },
  ],

  // Manual sidebar for the VLA Systems content
  module4Sidebar: [
    {
      type: 'category',
      label: 'Module 4: Vision-Language-Action (VLA) Systems',
      items: [
        'module-4/intro-to-vla',
        'module-4/voice-to-action-whisper',
        'module-4/cognitive-planning-llms',
      ],
    },
  ],
};

export default sidebars;
